import type { Metadata } from "next";
import { Open_Sans } from 'next/font/google'
import MainHeader from '@/app/components/MainHeader/MainHeader'
import MainFooter from '@/app/components/MainFooter/MainFooter'
import 'normalize.css';
import '@/app/assets/scss/theme-style.scss'

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const open_sans = Open_Sans({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={open_sans.className}>
			<body>
				<MainHeader />
				{children}
			</body>
		</html>
	);
}
